services:
  postgres:
    container_name: psql_vistar
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=bbGh8cnnmbUHo1okBipp'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpass
    command: server --console-address ":9001" /data
volumes:
  minio_storage: {}
  db:
    driver: local