spring:
  threads:
    virtual:
      enabled: true
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: bbGh8cnnmbUHo1okBipp
